name:
  pages
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Check format
        run: |
          npm run check-format
      - name: Lint
        run: |
          npm run lint
      - name: Build
        run: |
          npm run build
      - name: Push to `master` branch
        run: |
          rm ./docs/js/.gitignore
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout -B master
          git add .
          git commit --allow-empty -m "Publish to GitHub Pages"
          git push --force origin master
